/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AVAXConverter } from "./AVAXConverter";
export type { EERC20Converter } from "./EERC20Converter";
