// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { AVAXConverter$Type } from "./AVAXConverter";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["AVAXConverter"]: AVAXConverter$Type;
    ["contracts/AVAXConverter.sol:AVAXConverter"]: AVAXConverter$Type;
  }

  interface ContractTypesMap {
    ["AVAXConverter"]: GetContractReturnType<AVAXConverter$Type["abi"]>;
    ["contracts/AVAXConverter.sol:AVAXConverter"]: GetContractReturnType<AVAXConverter$Type["abi"]>;
  }
}
