// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { EERC20Converter$Type } from "./EERC20Converter";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["EERC20Converter"]: EERC20Converter$Type;
    ["contracts/EERC20Converter.sol:EERC20Converter"]: EERC20Converter$Type;
  }

  interface ContractTypesMap {
    ["EERC20Converter"]: GetContractReturnType<EERC20Converter$Type["abi"]>;
    ["contracts/EERC20Converter.sol:EERC20Converter"]: GetContractReturnType<EERC20Converter$Type["abi"]>;
  }
}
